#!/usr/bin/env bash
#Write a bash script that displays numbers from 1 to 100.
num=1
num_target=100
while [ $num -le $num_target ]; do
	if (( num % 3 == 0 )) && (( num % 5 == 0 )) ; then
	echo "Fizzbuzz"
elif (( num % 3 == 0 )) ; then
	echo "fizz"
elif (( num % 5 == 0 )) ; then
	echo "Buzz"
else
	echo $num
	fi
	((num=num+1))
done
