#!/usr/bin/env bash
#Write a bash script that displays the content of the file /etc/passwd.

passwd_file="/etc/passwd"

while IFS=: read -r username _ uid _ _ home _; do
echo "Username: $username"
echo "User ID: $uid"
echo "Home Directory: $home"
echo
done < "$passwd_file"
