#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes.
m=1 
h=0
while [ "$h" -le 12 ]
do
	echo "hour:$h"
        while [ "$m" -lt 60 ]
	do
		echo $m
		m=$((m+1)) 
	done
	h=$((h+1))
	m=1
done
